"""empty message

Revision ID: 0496a21dcd3a
Revises: 815ba758af91
Create Date: 2023-08-18 23:59:25.852012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0496a21dcd3a'
down_revision = '815ba758af91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_with_google')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_with_google', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
