"""empty message

Revision ID: 09141a3641c1
Revises: 308d3d410cc9
Create Date: 2023-06-25 15:59:18.594314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09141a3641c1'
down_revision = '308d3d410cc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_seller', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
