"""empty message

Revision ID: 27fc0a1bd768
Revises: 
Create Date: 2023-11-24 19:41:12.193965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fc0a1bd768'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_is_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('phone_number_verif_code', sa.Integer(), nullable=True),
    sa.Column('phone_number_is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_via_google', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('is_seller', sa.Boolean(), nullable=False),
    sa.Column('contacts', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('lots',
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=70), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('base_price', sa.Integer(), nullable=False),
    sa.Column('current_bid', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('lot_id')
    )
    op.create_index(op.f('ix_lots_lot_id'), 'lots', ['lot_id'], unique=False)
    op.create_table('bids',
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('bidder_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('placing_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ),
    sa.PrimaryKeyConstraint('bid_id')
    )
    op.create_index(op.f('ix_bids_bid_id'), 'bids', ['bid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bids_bid_id'), table_name='bids')
    op.drop_table('bids')
    op.drop_index(op.f('ix_lots_lot_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
