"""empty message

Revision ID: 308d3d410cc9
Revises: 33f0c9a4f7e5
Create Date: 2023-06-25 15:58:14.669848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308d3d410cc9'
down_revision = '33f0c9a4f7e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
