"""empty message

Revision ID: 4d830eea97dc
Revises: e39dd16c49f2
Create Date: 2023-10-04 20:21:58.916492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d830eea97dc'
down_revision: Union[str, None] = 'e39dd16c49f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lots', 'images',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lots', 'images',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
