"""empty message

Revision ID: 69c65c6e1f23
Revises: e8e7cdf0a2a0
Create Date: 2023-09-02 15:34:34.682059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c65c6e1f23'
down_revision = 'e8e7cdf0a2a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lots', 'images',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lots', 'images',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
