"""empty message

Revision ID: 6db09ec4c050
Revises: f3f96b0199fd
Create Date: 2023-10-31 19:31:14.630706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db09ec4c050'
down_revision: Union[str, None] = 'f3f96b0199fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'is_active')
    # ### end Alembic commands ###
