"""empty message

Revision ID: 700a69b6dea6
Revises: 69c65c6e1f23
Create Date: 2023-09-07 18:26:22.488340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700a69b6dea6'
down_revision = '69c65c6e1f23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('current_bid', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'current_bid')
    # ### end Alembic commands ###
