"""empty message

Revision ID: 7211b8e54e45
Revises: 821dca662a0c
Create Date: 2023-06-29 19:50:18.719002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7211b8e54e45'
down_revision = '821dca662a0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
