"""empty message

Revision ID: 7ee186985859
Revises: 8a873103e178
Create Date: 2023-10-31 14:17:09.083946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee186985859'
down_revision: Union[str, None] = '8a873103e178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('bidder_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('placing_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bidder_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ),
    sa.PrimaryKeyConstraint('bid_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    # ### end Alembic commands ###
