"""empty message

Revision ID: 815ba758af91
Revises: e0cbb1a3ab77
Create Date: 2023-08-18 23:45:04.949340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815ba758af91'
down_revision = 'e0cbb1a3ab77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_with_google', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_with_google')
    # ### end Alembic commands ###
