"""empty message

Revision ID: 821dca662a0c
Revises: 
Create Date: 2023-06-26 16:59:20.262852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821dca662a0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_is_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('phone_number_verif_code', sa.Integer(), nullable=True),
    sa.Column('phone_number_is_verified', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_seller', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
