"""empty message

Revision ID: 8a873103e178
Revises: 4d830eea97dc
Create Date: 2023-10-19 07:34:42.628428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a873103e178'
down_revision: Union[str, None] = '4d830eea97dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'reserve_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('reserve_price', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
