"""empty message

Revision ID: 963beb28223a
Revises: 09141a3641c1
Create Date: 2023-06-25 18:21:33.865212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '963beb28223a'
down_revision = '09141a3641c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
