"""empty message

Revision ID: ac1739cbc3ac
Revises: db1ecce8cc96
Create Date: 2023-08-24 15:03:39.796376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1739cbc3ac'
down_revision = 'db1ecce8cc96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
