"""empty message

Revision ID: ba8939d15a96
Revises: 963beb28223a
Create Date: 2023-06-25 20:04:49.809301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8939d15a96'
down_revision = '963beb28223a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email_is_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('phone_number_is_verified', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number_is_verified')
    op.drop_column('users', 'email_is_verified')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
