"""empty message

Revision ID: db1ecce8cc96
Revises: 0496a21dcd3a
Create Date: 2023-08-19 23:00:03.079271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1ecce8cc96'
down_revision = '0496a21dcd3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_via_google', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_via_google')
    # ### end Alembic commands ###
