"""empty message

Revision ID: e8e7cdf0a2a0
Revises: a960c90fd6e5
Create Date: 2023-09-02 15:31:36.706482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e7cdf0a2a0'
down_revision = 'a960c90fd6e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('images', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'images')
    # ### end Alembic commands ###
