"""empty message

Revision ID: f5969c1e0883
Revises: 13dc8ea3bcbf
Create Date: 2023-08-17 17:37:53.031259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5969c1e0883'
down_revision = '13dc8ea3bcbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
