name: Setup

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:

  server-tests:

    runs-on: ubuntu-latest

    services:
      
      postgres:

        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client

      - name: Get code
        uses: actions/checkout@v3

      - name: Initiate db for testing
        run: bash ./.github/scripts/create_test_db.sh

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installing requirements
        working-directory: server
        run: |
          pip install --upgrade pip
          python3.10 -m venv venv
          source venv/bin/activate
          pip install -r r.txt

      - name: Creating .env file
        run: echo "${{ secrets.TESTING_ENV }}" > dev.env

      - name: Run tests
        working-directory: server
        run: |
          source venv/bin/activate
          pytest
