name: Setup
on: workflow_dispatch
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Get python env
        working-directory: server
        run: |
          pip install --upgrade pip
          python3.10 -m venv venv
          source venv/bin/activate
      - name: Installing requirements
        run: pip install -r r.txt
