name: Setup
on: workflow_dispatch
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
  setup-server:
    runs-on: ubuntu-latest
    needs: [setup]
    defaults:
      run:
        shell: bash
        working-directory: server
    steps:
      - name: Get python env
        run: |
          pip install --upgrade pip
          python3.10 -m venv venv
          source venv/bin/activate
      - name: Installing requirements
        run: pip intall -r r.txt
