name: test
on: [push]
jobs:
  make-setup:
		runs-on: ubuntu-latest
		steps:
			- name: checkout
			  uses: actions/checkout@v3
			- name: intall npm packages
			  run: cd client && npm install && cd ..
			- name: install server requirements
			  run: cd server && sudo apt-get install python3-venv -y && python3 -m venv venv && source venv/bin/activate && pip install r.txt && cd ..
	run-server-tests:
		runs-on: ubuntu-latest
		needs: [setup]
		steps:
			- name: go to server dir
			  run: cd server
			- name: run tests
			  run: pytest --runslow
