name: test
on: [push]
jobs:
	job1:
		runs-on: ubuntu-latest
		steps:
			- name: test_step
			run: echo "job1"
	job2:
		runs-on: ubuntu-latest
		needs: [job1]
		steps:
			- name: test_step
			run: echo "job2"
